vich_uploader:
    db_driver: orm

    mappings:
        devise_images:
            uri_prefix: '%app.path.devise_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.devise_images%'